# ASCII Art: Cool Dog

print("             _ _")
print("____________/ / \\_.)_")
print("`.     ,'   @_@_/ ,'|")
print("  `-.-'        , / /|")
print("     `-.____,-'  | ||")
print("              \\  \\ ||")
print("              |  | \\|")
print("             /   \\     ,,'")
print("             |    \\   //")
print("            /      |  ||")
print("            |    ,-\\ //")
print("            |   _\\  \\||")
print("           (_`-(_____)/ ")
